package com.rokid.hud.shared.protocol

object ProtocolConstants {
    const val FIELD_TYPE = "t"
    const val FIELD_LATITUDE = "lat"
    const val FIELD_LONGITUDE = "lng"
    const val FIELD_BEARING = "bearing"
    const val FIELD_SPEED = "speed"
    const val FIELD_ACCURACY = "accuracy"
    const val FIELD_WAYPOINTS = "waypoints"
    const val FIELD_DISTANCE = "distance"
    const val FIELD_DURATION = "duration"
    const val FIELD_INSTRUCTION = "instruction"
    const val FIELD_MANEUVER = "maneuver"
    const val FIELD_STEP_DISTANCE = "stepDistance"
    const val FIELD_TITLE = "title"
    const val FIELD_TEXT = "text"
    const val FIELD_PACKAGE_NAME = "packageName"
    const val FIELD_TIME_MS = "timeMs"
    const val FIELD_TTS_ENABLED = "ttsEnabled"
    const val FIELD_USE_IMPERIAL = "useImperial"
    const val FIELD_USE_MINI_MAP = "useMiniMap"
    const val FIELD_MINI_MAP_STYLE = "miniMapStyle"
    const val FIELD_STREAM_NOTIFICATIONS = "streamNotifs"
    const val FIELD_SHOW_UPCOMING_STEPS = "showUpcoming"
    const val FIELD_STEPS = "steps"
    const val FIELD_CURRENT_INDEX = "curIdx"
    const val FIELD_WIFI_SSID = "wifiSsid"
    const val FIELD_WIFI_PASS = "wifiPass"
    const val FIELD_WIFI_ENABLED = "wifiEnabled"
    const val FIELD_TILE_ID = "id"
    const val FIELD_TILE_Z = "z"
    const val FIELD_TILE_X = "x"
    const val FIELD_TILE_Y = "y"
    const val FIELD_TILE_DATA = "data"
    const val FIELD_APK_SIZE = "apkSize"
    const val FIELD_APK_CHUNKS = "apkChunks"
    const val FIELD_APK_INDEX = "apkIdx"

    object MessageType {
        const val STATE = "state"
        const val ROUTE = "route"
        const val STEP = "step"
        const val NOTIFICATION = "notification"
        const val SETTINGS = "settings"
        const val WIFI_CREDS = "wifi_creds"
        const val TILE_REQ = "tile_req"
        const val TILE_RESP = "tile_resp"
        const val APK_START = "apk_start"
        const val APK_CHUNK = "apk_chunk"
        const val APK_END = "apk_end"
        const val STEPS_LIST = "steps_list"
    }
}
